'use client'
import { useState, useCallback, useMemo } from 'react'
import { useCanvasStore } from '@/lib/canvas/store'
import type { CanvasNode, CanvasEdge } from '@/lib/canvas/jsoncanvas'

// ─── local types ────────────────────────────────────────────────────────────

type FilterKind = 'all' | 'nodes' | 'edges' | 'files' | 'comments'
type BadgeKind  = 'add' | 'upd' | 'rem'

interface DiffEntry {
  key:       string
  badge:     BadgeKind
  name:      string
  kindLabel: string
  category:  'nodes' | 'edges' | 'files' | 'comments'
}

// ─── display-name helpers ────────────────────────────────────────────────────

function nodeDisplayName(n: CanvasNode): string {
  if (n.type === 'file') {
    const parts = n.file.replace(/\\/g, '/').split('/')
    return parts[parts.length - 1] ?? n.file
  }
  if (n.type === 'link')  return n.url
  if (n.type === 'group') return n.label || n.id
  if (n.type === 'text')  return n.text.split('\n')[0].slice(0, 48) || n.id
  return (n as CanvasNode).id
}

function nodeKindLabel(n: CanvasNode): string {
  if (n.type === 'file') {
    const ext = n.file.split('.').pop()?.toLowerCase()
    return `node · ${ext ?? 'file'}`
  }
  if (n.type === 'link')  return 'node · link'
  if (n.type === 'text')  return 'node · text'
  if (n.type === 'group') return 'node · group'
  return 'node'
}

function edgeDisplayName(
  e:              CanvasEdge,
  byId:           Map<string, CanvasNode>,
  fallbackById:   Map<string, CanvasNode>,
): string {
  const name = (id: string) => {
    const n = byId.get(id) ?? fallbackById.get(id)
    return n ? nodeDisplayName(n) : id
  }
  const suffix = e.label
    ? ` · ${e.label}`
    : e.meta?.rel ? ` · ${e.meta.rel}` : ''
  return `${name(e.fromNode)} → ${name(e.toNode)}${suffix}`
}

// ─── entry builder ───────────────────────────────────────────────────────────

interface DiffShape {
  nodes:    { added: string[]; updated: string[]; removed: string[] }
  edges:    { added: string[]; updated: string[]; removed: string[] }
  comments: { added: string[] }
  files:    string[]
}

function buildEntries(
  diff:             DiffShape,
  docNodeById:      Map<string, CanvasNode>,
  snapNodeById:     Map<string, CanvasNode>,
  docEdgeById:      Map<string, CanvasEdge>,
  snapEdgeById:     Map<string, CanvasEdge>,
  commentTextById:  Map<string, string>,
): DiffEntry[] {
  const out: DiffEntry[] = []

  // nodes
  for (const id of diff.nodes.added) {
    const n = docNodeById.get(id)
    out.push({ key: `na-${id}`, badge: 'add', name: n ? nodeDisplayName(n) : id, kindLabel: n ? nodeKindLabel(n) : 'node', category: 'nodes' })
  }
  for (const id of diff.nodes.updated) {
    const n = docNodeById.get(id)
    out.push({ key: `nu-${id}`, badge: 'upd', name: n ? nodeDisplayName(n) : id, kindLabel: n ? nodeKindLabel(n) : 'node', category: 'nodes' })
  }
  for (const id of diff.nodes.removed) {
    const n = snapNodeById.get(id)
    out.push({ key: `nr-${id}`, badge: 'rem', name: n ? nodeDisplayName(n) : id, kindLabel: n ? nodeKindLabel(n) : 'node', category: 'nodes' })
  }

  // edges
  for (const id of diff.edges.added) {
    const e = docEdgeById.get(id)
    out.push({ key: `ea-${id}`, badge: 'add', name: e ? edgeDisplayName(e, docNodeById, snapNodeById) : id, kindLabel: 'edge', category: 'edges' })
  }
  for (const id of diff.edges.updated) {
    const e = docEdgeById.get(id)
    out.push({ key: `eu-${id}`, badge: 'upd', name: e ? edgeDisplayName(e, docNodeById, snapNodeById) : id, kindLabel: 'edge · rel', category: 'edges' })
  }
  for (const id of diff.edges.removed) {
    const e = snapEdgeById.get(id)
    out.push({ key: `er-${id}`, badge: 'rem', name: e ? edgeDisplayName(e, docNodeById, snapNodeById) : id, kindLabel: 'edge', category: 'edges' })
  }

  // comments
  for (const id of diff.comments.added) {
    const text = commentTextById.get(id)
    out.push({ key: `ca-${id}`, badge: 'add', name: text ? `"${text.slice(0, 40)}"` : id, kindLabel: 'comment', category: 'comments' })
  }

  // files (generated by the round — discard deletes them)
  for (const path of diff.files) {
    const parts = path.replace(/\\/g, '/').split('/')
    out.push({ key: `f-${path}`, badge: 'add', name: parts[parts.length - 1] ?? path, kindLabel: 'file', category: 'files' })
  }

  return out
}

// ─── component ───────────────────────────────────────────────────────────────

export function ReviewPanel({ onClose }: { onClose: () => void }) {
  const [filter, setFilter] = useState<FilterKind>('all')
  const [step,   setStep]   = useState(0)

  const getReviewDiff = useCanvasStore((s) => s.reviewDiff)
  const acceptRound   = useCanvasStore((s) => s.acceptRound)
  const discardRound  = useCanvasStore((s) => s.discardRound)
  const doc           = useCanvasStore((s) => s.doc)
  const reviewState   = useCanvasStore((s) => s.reviewState)

  // Build the flat entry list whenever doc or reviewState changes.
  // getReviewDiff is a stable action reference (Zustand guarantees this).
  const entries = useMemo<DiffEntry[]>(() => {
    const diff = getReviewDiff()
    if (!diff || !doc || !reviewState) return []
    const docNodeById     = new Map(doc.nodes.map((n) => [n.id, n]))
    const snapNodeById    = new Map(reviewState.snapshot.nodes.map((n) => [n.id, n]))
    const docEdgeById     = new Map(doc.edges.map((e) => [e.id, e]))
    const snapEdgeById    = new Map(reviewState.snapshot.edges.map((e) => [e.id, e]))
    const commentTextById = new Map(doc.flowcanvas.comments.map((c) => [c.id, c.text]))
    return buildEntries(diff, docNodeById, snapNodeById, docEdgeById, snapEdgeById, commentTextById)
  }, [getReviewDiff, doc, reviewState])

  const filtered = useMemo(
    () => (filter === 'all' ? entries : entries.filter((e) => e.category === filter)),
    [entries, filter],
  )

  // Clamp the active step so stale index values from a previous filter don't go OOB.
  const activeStep = filtered.length === 0 ? 0 : Math.min(step, filtered.length - 1)

  const countFor = useCallback(
    (kind: FilterKind) =>
      kind === 'all' ? entries.length : entries.filter((e) => e.category === kind).length,
    [entries],
  )

  const changeFilter = useCallback((f: FilterKind) => {
    setFilter(f)
    setStep(0)
  }, [])

  const prev = useCallback(() => setStep((s) => Math.max(0, s - 1)), [])
  const next = useCallback(
    () => setStep((s) => Math.min(filtered.length - 1, s + 1)),
    [filtered.length],
  )

  const handleAccept = useCallback(async () => {
    await acceptRound()
    onClose()
  }, [acceptRound, onClose])

  const handleDiscard = useCallback(async () => {
    await discardRound()
    onClose()
  }, [discardRound, onClose])

  const hasPendingRound = reviewState !== null

  return (
    <div
      className="fc-review"
      data-testid="review-panel"
      role="region"
      aria-label="Agent change-review"
    >
      {/* Header */}
      <div className="fc-review__hd">
        <div>
          <b className="fc-review__title">Change-review</b>
          {reviewState && (
            <div className="fc-review__sub">
              snapshot rev {reviewState.baseRevision}
            </div>
          )}
        </div>
        <button
          className="fc-review__x"
          data-testid="review-close"
          aria-label="Close review"
          onClick={onClose}
        >
          ✕
        </button>
      </div>

      {/* Empty state — no pending round. #1: explain what change-review is for (agent rounds) and point
          local edits at undo/redo, so the tab never reads as "useless / I changed things and nothing here". */}
      {!hasPendingRound && (
        <div className="fc-review__empty" data-testid="review-empty">
          <p className="fc-review__empty-h">No agent round to review</p>
          <p className="fc-review__empty-p">
            Change-review lists what the <strong>agent</strong> added, updated, or removed in its last round.
            It appears here after the agent applies changes over MCP.
          </p>
          <p className="fc-review__empty-p">
            Editing the board yourself? Those changes apply live — use <strong>Undo (⌘Z)</strong> and{' '}
            <strong>Redo (⌘⇧Z)</strong> to step back and forward.
          </p>
        </div>
      )}

      {/* Diff body + footer */}
      {hasPendingRound && (
        <>
          <div className="fc-review__body">
            {/* Filter row */}
            <div className="fc-review__filters" role="group" aria-label="Filter changes">
              {(['all', 'nodes', 'edges', 'files', 'comments'] as const).map((f) => (
                <button
                  key={f}
                  data-testid={`review-filter-${f}`}
                  aria-pressed={filter === f}
                  className="fc-review__filter-btn"
                  onClick={() => changeFilter(f)}
                >
                  {f} · {countFor(f)}
                </button>
              ))}
            </div>

            {/* Stepper */}
            {filtered.length > 0 && (
              <div className="fc-review__stepper">
                <button
                  className="fc-review__ghost"
                  data-testid="review-prev"
                  aria-label="Previous change"
                  onClick={prev}
                  disabled={activeStep === 0}
                >
                  ‹
                </button>
                <button
                  className="fc-review__ghost"
                  data-testid="review-next"
                  aria-label="Next change"
                  onClick={next}
                  disabled={activeStep >= filtered.length - 1}
                >
                  ›
                </button>
                <span className="fc-review__pos">
                  {activeStep + 1} / {filtered.length}
                </span>
              </div>
            )}

            {/* Item list */}
            <div className="fc-review__list">
              {filtered.map((entry, i) => (
                <div
                  key={entry.key}
                  className={`fc-review__item${i === activeStep ? ' active' : ''}`}
                  data-testid="review-item"
                  tabIndex={0}
                  onClick={() => setStep(i)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      setStep(i)
                    }
                  }}
                >
                  <div className="fc-review__item-top">
                    <span className={`fc-review__badge fc-review__badge--${entry.badge}`}>
                      {entry.badge === 'add'
                        ? 'added'
                        : entry.badge === 'upd'
                          ? 'updated'
                          : 'removed'}
                    </span>
                    <span className="fc-review__name">{entry.name}</span>
                    <span className="fc-review__kind">{entry.kindLabel}</span>
                  </div>
                </div>
              ))}

              {filtered.length === 0 && (
                <p className="fc-review__no-items">No {filter} changes</p>
              )}
            </div>
          </div>

          {/* Footer */}
          <div className="fc-review__foot">
            <button
              className="fc-review__btn-discard"
              data-testid="review-discard"
              onClick={() => void handleDiscard()}
            >
              Discard
            </button>
            <button
              className="fc-review__btn-accept"
              data-testid="review-accept"
              onClick={() => void handleAccept()}
            >
              Accept all {entries.length}
            </button>
          </div>
        </>
      )}
    </div>
  )
}
