#!/usr/bin/env bash
#
# analyze-session.sh — read-only session-evidence gatherer for the feedback loop.
#
# Step 1 of the flowcode:feedback skill needs the same raw evidence every run:
# what changed in the working tree, which hooks fired with block/warn, and where
# the plan/project logs already stand. Re-deriving those commands by hand each
# session is wasteful and drifts; this script gathers them in one deterministic
# pass and prints a digest. It makes NO judgments and writes NOTHING — the agent
# still decides what is a candidate, where it routes, and apply-vs-log.
#
# Usage:  bash scripts/analyze-session.sh ["optional focus string"]
# Run from the host project root (the directory that contains .flowcode/).
#
# Exit codes: always 0 (a missing git repo or log is reported, not fatal — the
# agent supplements with conversation-only candidates regardless).

set -u

FOCUS="${1:-}"

# Resolve the flowcode root: .flowcode/ in a host install, flowcode/ in the dev repo.
FC=""
if [ -d ".flowcode" ]; then
  FC=".flowcode"
elif [ -d "flowcode" ]; then
  FC="flowcode"
fi

LOGS_DIR="${FC:+$FC/logs}"
PLANS_DIR="${FC:+$FC/plans}"
PROJECT_LOG="${FC:+$FC/project/project-log.md}"

section() {
  printf '\n===== %s =====\n' "$1"
}

printf '########## FEEDBACK SESSION DIGEST ##########\n'
printf 'generated by: scripts/analyze-session.sh (read-only)\n'
printf 'cwd: %s\n' "$(pwd)"
printf 'flowcode root: %s\n' "${FC:-<none found>}"
[ -n "$FOCUS" ] && printf 'focus: %s\n' "$FOCUS"

# ── Working-tree changes across the WHOLE repo (not only .flowcode/) ──────────
section "GIT STATUS (whole repo, porcelain)"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  status="$(git status --porcelain --untracked-files=all 2>/dev/null)"
  if [ -n "$status" ]; then
    printf '%s\n' "$status"
  else
    printf '(clean working tree — look to the conversation for decisions/conventions)\n'
  fi

  section "GIT DIFF --stat (working tree + staged, max 60 lines)"
  diffstat="$( { git diff --stat 2>/dev/null; git diff --cached --stat 2>/dev/null; } | head -60)"
  [ -n "$diffstat" ] && printf '%s\n' "$diffstat" || printf '(no tracked-file modifications)\n'
else
  printf '(not a git repository — skipping git evidence)\n'
fi

# ── Hooks that fired with block/warn this session ────────────────────────────
section "HOOKS.LOG — recent block/warn (last 30)"
if [ -n "$LOGS_DIR" ] && [ -f "$LOGS_DIR/hooks.log" ]; then
  hits="$(grep -Ei '	(block|warn)' "$LOGS_DIR/hooks.log" 2>/dev/null | tail -30)"
  [ -n "$hits" ] && printf '%s\n' "$hits" || printf '(no block/warn outcomes logged)\n'
else
  printf '(no hooks.log found under %s)\n' "${LOGS_DIR:-<no flowcode root>}"
fi

# ── Head of the most-recently-touched plan log ───────────────────────────────
section "ACTIVE PLAN LOG (head, 40 lines)"
if [ -n "$PLANS_DIR" ] && [ -d "$PLANS_DIR" ]; then
  latest_plan_log="$(ls -t "$PLANS_DIR"/*/*-log.md 2>/dev/null | head -1)"
  if [ -n "$latest_plan_log" ]; then
    printf '# %s\n' "$latest_plan_log"
    head -40 "$latest_plan_log"
  else
    printf '(no {PREFIX}-log.md under %s)\n' "$PLANS_DIR"
  fi
else
  printf '(no plans directory found)\n'
fi

# ── Head of the project log (so already-recorded items are not re-captured) ───
section "PROJECT LOG (head, 40 lines)"
if [ -n "$PROJECT_LOG" ] && [ -f "$PROJECT_LOG" ]; then
  head -40 "$PROJECT_LOG"
else
  printf '(no project-log.md found at %s)\n' "${PROJECT_LOG:-<no flowcode root>}"
fi

printf '\n########## END DIGEST ##########\n'
printf 'Next: reason over this digest AND the conversation. Conversation-only\n'
printf 'decisions/conventions are invisible here — add them as first-class candidates.\n'
exit 0
